### ISSUE TITLE
Add leetcode easy answer

### ISSUE THREAD

**Issue by RKC3000** [RKC3000/Java-Leet-Code-Solutions#5]

**Comment by PrathIam** [comment]
Hi @RKC3000, I am new here looking for my first contribution. Can I look into this?

**Comment by Git-Akshat01** [comment]
Hi! @RKC3000 Can you please assign me the task?
I have my solution ready.

**Comment by dishantzaveri** [comment]
Can you please assign me the task?

**Comment by RKC3000** [comment]
Done
